# Generated by Django 4.1.2 on 2022-10-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rezume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=250)),
                ('phone2', models.CharField(max_length=250)),
                ('Address', models.CharField(default='Kyrgyzstan', max_length=250)),
                ('profession', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
